# Generated by Django 4.2.7 on 2026-02-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='benefits',
            field=models.JSONField(default=list, help_text='List of key benefits/advantages'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_subtitle',
            field=models.TextField(default="Proforma Insights is Nepal's premier business & IT consultancy"),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_title',
            field=models.CharField(default='Leading Business Consultant in Nepal', max_length=300),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history_title',
            field=models.CharField(default='Our Journey', max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='values',
            field=models.JSONField(default=list, help_text='List of company values with title and description'),
        ),
    ]
