# Generated by Django 4.2.7 on 2026-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyinfo_benefits_companyinfo_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Closing paragraph'),
        ),
        migrations.AddField(
            model_name='insight',
            name='content_sections',
            field=models.JSONField(default=list, help_text="List of sections with heading and content. Format: [{'heading': 'Title', 'content': 'Text', 'points': ['point1', 'point2']}]"),
        ),
        migrations.AddField(
            model_name='insight',
            name='introduction',
            field=models.TextField(default='', help_text='Opening paragraph'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insight',
            name='content',
            field=models.TextField(blank=True, help_text='Legacy full content field'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='insights/'),
        ),
    ]
