# Generated by Django 4.2.7 on 2026-02-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_insight_conclusion_insight_content_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='content_blocks',
            field=models.JSONField(default=list, help_text="List of content blocks. Format: [{'type': 'heading'|'paragraph'|'list', 'content': 'text' or ['item1', 'item2']}]"),
        ),
        migrations.AlterField(
            model_name='insight',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Legacy conclusion field'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='content_sections',
            field=models.JSONField(blank=True, default=list, help_text='Legacy sections field'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='introduction',
            field=models.TextField(blank=True, help_text='Legacy introduction field'),
        ),
    ]
