# Generated by Django 4.2.7 on 2026-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_insight_content_blocks_alter_insight_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Legacy: Closing paragraph'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='content',
            field=models.TextField(blank=True, help_text='Legacy: Full content field'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='content_blocks',
            field=models.JSONField(default=list, help_text='Content blocks with type and content. Types: paragraph, heading, list'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='content_sections',
            field=models.JSONField(blank=True, default=list, help_text='Legacy: Structured sections'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='introduction',
            field=models.TextField(blank=True, help_text='Legacy: Opening paragraph'),
        ),
    ]
