# Generated by Django 4.2.7 on 2026-02-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_insight_conclusion_alter_insight_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g., Crosshair, Star, Rocket)', max_length=50)),
                ('content_blocks', models.JSONField(default=list, help_text='Content blocks with type and content. Types: paragraph, heading, list')),
                ('image', models.ImageField(blank=True, null=True, upload_to='proforma_cards/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proforma Card',
                'verbose_name_plural': 'Proforma Cards',
                'ordering': ['order', 'title'],
            },
        ),
    ]
