# Generated by Django 4.2.7 on 2026-02-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proformacard'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(default='#0066cc', help_text='Service theme color', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='detail_content',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed page content with sections, lists, and images'),
        ),
    ]
