# Generated by Django 4.2.7 on 2026-02-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_color_service_detail_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='Detail page image', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle for detail page hero section'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Title for detail page hero section', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='services_list',
            field=models.JSONField(default=list, help_text='List of specific services offered'),
        ),
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(default='#0066cc', help_text='Hex color code for the service', max_length=7),
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_content',
            field=models.TextField(blank=True, help_text='Main content for detail page'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Card image', null=True, upload_to='services/'),
        ),
    ]
