# Generated by Django 4.2.7 on 2026-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_detail_image_service_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.JSONField(default=list, help_text='List of key features. Can be simple strings or objects with "title" and "description" keys'),
        ),
    ]
