# Generated by Django 4.2.7 on 2026-02-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_service_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle for main content section', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.JSONField(default=list, help_text='List of key features'),
        ),
    ]
