# Generated by Django 4.2.7 on 2026-02-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_detail_subtitle_alter_service_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g., Award, Users, Target)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkEnvironmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='work_environment/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Work Environment Image',
                'verbose_name_plural': 'Work Environment Images',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='detail_subtitle',
        ),
    ]
