# Generated by Django 4.2.7 on 2026-02-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_corevalue_workenvironmentimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='icon_name',
            field=models.CharField(help_text='Lucide icon name. Suggestions: Award (Excellence), Target (Goals), Users (Teamwork), Shield (Integrity), Heart (Care), Lightbulb (Innovation), TrendingUp (Growth), CheckCircle (Quality), Handshake (Trust), Zap (Efficiency)', max_length=50),
        ),
    ]
