# Generated by Django 4.2.7 on 2026-02-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_corevalue_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Key Advantage',
                'verbose_name_plural': 'Key Advantages',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_title', models.CharField(default='Your Trusted Partner', max_length=200)),
                ('partner_description', models.TextField(help_text='Main paragraph describing why clients should choose you')),
                ('point_1_title', models.CharField(default='Expert Guidance', max_length=200)),
                ('point_1_description', models.CharField(default='Professional advice from experienced consultants', max_length=300)),
                ('point_2_title', models.CharField(default='Innovative Solutions', max_length=200)),
                ('point_2_description', models.CharField(default='Cutting-edge approaches to business challenges', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Content',
                'verbose_name_plural': 'Why Choose Us Content',
            },
        ),
    ]
