# Generated by Django 4.2.7 on 2026-02-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_keyadvantage_whychooseus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyAdvantage',
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='key_advantages',
            field=models.JSONField(default=list, help_text="List of key advantages/benefits (e.g., ['Deep understanding of Nepali business', 'Experienced team'])"),
        ),
    ]
