# Generated by Django 4.2.7 on 2026-02-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_keyadvantage_whychooseus_key_advantages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseus',
            name='point_1_description',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='point_1_title',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='point_2_description',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='point_2_title',
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='numbered_points',
            field=models.JSONField(default=list, help_text='List of numbered points with title and description. Example: [{"title": "Expert Guidance", "description": "Professional advice from experienced consultants"}, {"title": "Innovative Solutions", "description": "Cutting-edge approaches"}]'),
        ),
    ]
