# Generated by Django 4.2.7 on 2026-02-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_whychooseus_point_1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_post_url', models.URLField(blank=True, help_text='Facebook post embed URL (e.g., https://www.facebook.com/plugins/post.php?href=...)')),
                ('instagram_post_url', models.URLField(blank=True, help_text='Instagram post embed URL (e.g., https://www.instagram.com/p/POST_ID/embed)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Posts',
                'verbose_name_plural': 'Social Media Posts',
            },
        ),
    ]
