# Generated by Django 4.2.7 on 2026-02-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_socialmediapost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaPost',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='facebook_embed_code',
            field=models.TextField(blank=True, help_text="Paste the full Facebook embed iframe code here (e.g., <iframe src='...'></iframe>)"),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='instagram_embed_code',
            field=models.TextField(blank=True, help_text="Paste the full Instagram embed iframe code here (e.g., <iframe src='...'></iframe>)"),
        ),
    ]
