# Generated by Django 4.2.7 on 2026-02-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_socialmediapost_and_more'),
    ]

    operations = [
    ]
