# Generated by Django 4.2.7 on 2026-02-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20260210_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title for admin reference', max_length=200)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('embed_code', models.TextField(help_text="Paste the full iframe embed code from Facebook/Instagram (e.g., <iframe src='...'></iframe>)")),
                ('post_url', models.URLField(blank=True, help_text='Direct link to the post (optional, for fallback)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='facebook_embed_code',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='instagram_embed_code',
        ),
    ]
