# Generated by Django 4.2.7 on 2026-02-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_socialmediapost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='embed_code',
            field=models.TextField(help_text="Paste the full iframe embed code from Facebook/Instagram/YouTube (e.g., <iframe src='...'></iframe>)"),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn')], max_length=20),
        ),
    ]
