# Generated by Django 4.2.7 on 2026-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_socialmediapost_embed_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_tag', models.CharField(default='Financial Services', max_length=100)),
                ('accounting_title', models.CharField(default='Accounting & Tax Solutions', max_length=200)),
                ('accounting_description', models.TextField(default='Expert bookkeeping, financial analysis, tax planning, and compliance management to keep your business financially sound and regulation-ready.')),
                ('accounting_features', models.JSONField(default=list, help_text='List of features for accounting panel. Example: [{"icon": "BookOpen", "text": "Bookkeeping"}, {"icon": "TrendingUp", "text": "Financial Analysis"}]')),
                ('accounting_button1_text', models.CharField(default='Accounting Services', max_length=50)),
                ('accounting_button1_link', models.CharField(default='/accounting', max_length=200)),
                ('accounting_button2_text', models.CharField(default='Tax Services', max_length=50)),
                ('accounting_button2_link', models.CharField(default='/tax', max_length=200)),
                ('it_tag', models.CharField(default='Technology Solutions', max_length=100)),
                ('it_title', models.CharField(default='IT & Digital Transformation', max_length=200)),
                ('it_description', models.TextField(default='Strategic IT consulting, cybersecurity, cloud solutions, and digital marketing to accelerate your business into the future.')),
                ('it_features', models.JSONField(default=list, help_text='List of features for IT panel. Example: [{"icon": "Code", "text": "Software Dev"}, {"icon": "Lock", "text": "Cybersecurity"}]')),
                ('it_button1_text', models.CharField(default='IT Services', max_length=50)),
                ('it_button1_link', models.CharField(default='/it', max_length=200)),
                ('it_button2_text', models.CharField(default='Digital Services', max_length=50)),
                ('it_button2_link', models.CharField(default='/digital', max_length=200)),
                ('hero_title', models.CharField(default='The Remote and Physical Business Consultancy With All Related IT Services', max_length=300)),
                ('hero_subtitle', models.CharField(default='Professional consultancy to drive business growth and profitability', max_length=300)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section image (defaults to proforma-office.jpg if not set)', null=True, upload_to='homepage/')),
                ('hero_features', models.JSONField(default=list, help_text='List of hero features. Example: [{"text": "Expert Consultants"}, {"text": "Proven Solutions"}, {"text": "24/7 Support"}]')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
    ]
