# Generated by Django 4.2.7 on 2026-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Web Development, Accounting, IT Solutions', max_length=100)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of technologies used')),
                ('project_url', models.URLField(blank=True, help_text='Live project URL')),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
