# Generated by Django 4.2.7 on 2026-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g., Calculator, Monitor, Shield)', max_length=50)),
                ('image', models.ImageField(upload_to='homepage_services/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Service',
                'verbose_name_plural': 'Homepage Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
